### ISSUE TITLE
toolchain job is pulling base image twice

### ISSUE THREAD

**Issue by tgross** [plan-systems/plan-ci#4]
There's an inefficiency in the pipeline when we build the toolchain image, where we end up pulling the base image twice. Under heavy load this ends up creating a lot of extraneous disk IO and slows everything down.

**Comment by tgross** [comment]
While debugging auth on our http-publish, I noted this: https://concourse-ci.org/put-step.html

> Additionally, you can control the settings of the implicit get step by setting get_params. For example, if you did not want a put step utilizing the docker-image resource type to download the image, you would implement your put step as such:
```
plan:
- put: docker-build
  params: {build: git-resource}
  get_params: {skip_download: true}
```

So I think that's the way to avoid this.
